/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package agent.smith;

import org.junit.Test;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertTrue;

public class MatrixTest {

    @Test
    public void testMatrixConstructorMatrix() {
        Matrix M = new Matrix(new double[][]{{1, 2}, {3, 4}});
        double[][] expected = {{1, 2}, {3, 4}};

        Matrix matrix = new Matrix(M);

        assertArrayEquals(expected, matrix.viewArray());
    }
}

